version: "3.8"

services:
  vue-project:
    container_name: vue-project
    image: vue-project
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/app

networks:
  default:
    external: true
    name: default-network
      